# Generated by Django 4.2.5 on 2023-09-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2023-05-21'),
            preserve_default=False,
        ),
    ]
